### PR TITLE
Additional error handler

### PR DESCRIPTION
**Pull request by BluewyDev**

### CODE REVIEW

**Comment by Alex0622** [comment]
I've tried it and the bot does not send the embed, it should be something like this:
`@bot.event
async def on_command_error(ctx, err):
    if isinstance(err, commands.CommandNotFound):
        embed = discord.Embed(description=str(err), color=discord.Color.red())
        await ctx.send(embed=embed)`

**Comment by Alex0622** [comment]
Also you forgot to add a ":" in async def on_command_error(ctx, err)

**Comment by Alex0622** [comment]
Still, it doesn't send the embed. What you have to do is remove the **else**, it is not needed, is the same for **pas**.
What you want to do is to send the embed if the command is not found, but what you are doing in that code is to ignore the error if the command is not found.

**Comment by Alex0622** [comment]
I have added the error handler, thanks for you suggestion tho.

**Comment by BluewyDev** [comment]
> Still, it doesn't send the embed. What you have to do is remove the **else**, it is not needed, is the same for **pas**.
> What you want to do is to send the embed if the command is not found, but what you are doing in that code is to ignore the error if the command is not found.

Followup, you want an embed to show up for whenever someone tries to use a command that doesn't exist?
Just saying but for public bots that's generally not a good practise and not a lot of people will like that.

**Comment by Alex0622** [comment]
Well, weren't you the one who made the suggestion? Also, if your intention is not not send an embed when the command is not found, then why would make an embed anyway? You could have just printed the error or something.

**Comment by BluewyDev** [comment]
That's... Essentially what you did

I don't think you get what this does

The `pass` doesn't send anything, the pass just mean it basically ignores when the command isn't found. The embed only sends on any other error occasion EXCEPT CommandNotFound

**Comment by Alex0622** [comment]
I know what `pass` does, and I think I get your point know, I will add this in a new update, thanks for your suggestion.

**Comment by Alex0622** [comment]
Alright, I have released the new update, you can find it [here](https://github.com/Alex0622/Al3xis-Bot-dev/releases/tag/v1.3.2)
Thanks for your suggestion.

**Pull request closed without merging**
